global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: devices
    static_configs:
      - targets: ['host.docker.internal:8000']